- id: '1601928702439'
  alias: Télécommande du store du bureau - Bouton "Ouvert" appuyé
  description: ''
  trigger:
  - device_id: 3a52bba6074611eb8b0e371c90bad458
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: open
  condition: []
  action:
  - device_id: 3a52ea7c074611ebb490615e5de8fd22
    domain: cover
    entity_id: cover.store_du_bureau
    type: set_position
    position: 100
  mode: single
- id: '1601928849126'
  alias: Télécommande du store du bureau - Bouton "Fermé" appuyé
  description: ''
  trigger:
  - device_id: 3a52bba6074611eb8b0e371c90bad458
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: close
  condition: []
  action:
  - device_id: 3a52ea7c074611ebb490615e5de8fd22
    domain: cover
    entity_id: cover.store_du_bureau
    type: set_position
    position: 1
  mode: single
