homeassistant:
  customize:
    switch.kitchen_coffee_and_tea:
      friendly_name: Coffee & Tea
    sensor.kitchen_coffee_and_tea_consumption:
      friendly_name: Coffee & Tea - Consommation
    sensor.kitchen_coffee_and_tea_power:
      friendly_name: Coffee & Tea - Puissance
    cover.office_roller_blind:
      friendly_name: Store du bureau
    sensor.office_roller_blind_battery_level:
      friendly_name: Store du bureau - Batterie
    cover.bedroom_roller_blind:
      friendly_name: Store de la chambre
    sensor.bedroom_roller_blind_battery_level:
      friendly_name: Store de la chambre - Batterie
    cover.emma_bedroom_roller_blind:
      friendly_name: Store de la chambre d'Emma
    sensor.emma_bedroom_roller_blind_battery_level:
      friendly_name: Store de la chambre d'Emma - Batterie
